// css-utilities.js
// A comprehensive list of CSS properties for the Smart Editor autocompletion
// Import into your Svelte component: import { completionList } from './css-utilities.js'

export const completionList = [
	// ─── Layout & Display ───
	{ word: 'display', insert: 'display: ;', cursorOffset: -1 },
	{ word: 'position', insert: 'position: ;', cursorOffset: -1 },
	{ word: 'top', insert: 'top: ;', cursorOffset: -1 },
	{ word: 'right', insert: 'right: ;', cursorOffset: -1 },
	{ word: 'bottom', insert: 'bottom: ;', cursorOffset: -1 },
	{ word: 'left', insert: 'left: ;', cursorOffset: -1 },
	{ word: 'z-index', insert: 'z-index: ;', cursorOffset: -1 },
	{ word: 'float', insert: 'float: ;', cursorOffset: -1 },
	{ word: 'clear', insert: 'clear: ;', cursorOffset: -1 },
	{ word: 'visibility', insert: 'visibility: ;', cursorOffset: -1 },
	{ word: 'overflow', insert: 'overflow: ;', cursorOffset: -1 },
	{ word: 'overflow-x', insert: 'overflow-x: ;', cursorOffset: -1 },
	{ word: 'overflow-y', insert: 'overflow-y: ;', cursorOffset: -1 },
	{ word: 'clip', insert: 'clip: ;', cursorOffset: -1 },
	{ word: 'clip-path', insert: 'clip-path: ;', cursorOffset: -1 },
	{ word: 'opacity', insert: 'opacity: ;', cursorOffset: -1 },
	{ word: 'cursor', insert: 'cursor: ;', cursorOffset: -1 },
	{ word: 'pointer-events', insert: 'pointer-events: ;', cursorOffset: -1 },
	{ word: 'user-select', insert: 'user-select: ;', cursorOffset: -1 },
	{ word: 'resize', insert: 'resize: ;', cursorOffset: -1 },
	{ word: 'aspect-ratio', insert: 'aspect-ratio: ;', cursorOffset: -1 },
	{ word: 'object-fit', insert: 'object-fit: ;', cursorOffset: -1 },
	{ word: 'object-position', insert: 'object-position: ;', cursorOffset: -1 },
	{ word: 'isolation', insert: 'isolation: ;', cursorOffset: -1 },
	{ word: 'mix-blend-mode', insert: 'mix-blend-mode: ;', cursorOffset: -1 },

	// ─── Flexbox ───
	{ word: 'flex', insert: 'flex: ;', cursorOffset: -1 },
	{ word: 'flex-direction', insert: 'flex-direction: ;', cursorOffset: -1 },
	{ word: 'flex-wrap', insert: 'flex-wrap: ;', cursorOffset: -1 },
	{ word: 'flex-flow', insert: 'flex-flow: ;', cursorOffset: -1 },
	{ word: 'justify-content', insert: 'justify-content: ;', cursorOffset: -1 },
	{ word: 'align-items', insert: 'align-items: ;', cursorOffset: -1 },
	{ word: 'align-content', insert: 'align-content: ;', cursorOffset: -1 },
	{ word: 'align-self', insert: 'align-self: ;', cursorOffset: -1 },
	{ word: 'order', insert: 'order: ;', cursorOffset: -1 },
	{ word: 'flex-grow', insert: 'flex-grow: ;', cursorOffset: -1 },
	{ word: 'flex-shrink', insert: 'flex-shrink: ;', cursorOffset: -1 },
	{ word: 'flex-basis', insert: 'flex-basis: ;', cursorOffset: -1 },
	{ word: 'gap', insert: 'gap: ;', cursorOffset: -1 },
	{ word: 'row-gap', insert: 'row-gap: ;', cursorOffset: -1 },
	{ word: 'column-gap', insert: 'column-gap: ;', cursorOffset: -1 },

	// ─── Grid ───
	{ word: 'grid', insert: 'grid: ;', cursorOffset: -1 },
	{ word: 'grid-template', insert: 'grid-template: ;', cursorOffset: -1 },
	{ word: 'grid-template-columns', insert: 'grid-template-columns: ;', cursorOffset: -1 },
	{ word: 'grid-template-rows', insert: 'grid-template-rows: ;', cursorOffset: -1 },
	{ word: 'grid-template-areas', insert: 'grid-template-areas: ;', cursorOffset: -1 },
	{ word: 'grid-column', insert: 'grid-column: ;', cursorOffset: -1 },
	{ word: 'grid-column-start', insert: 'grid-column-start: ;', cursorOffset: -1 },
	{ word: 'grid-column-end', insert: 'grid-column-end: ;', cursorOffset: -1 },
	{ word: 'grid-row', insert: 'grid-row: ;', cursorOffset: -1 },
	{ word: 'grid-row-start', insert: 'grid-row-start: ;', cursorOffset: -1 },
	{ word: 'grid-row-end', insert: 'grid-row-end: ;', cursorOffset: -1 },
	{ word: 'grid-area', insert: 'grid-area: ;', cursorOffset: -1 },
	{ word: 'grid-auto-columns', insert: 'grid-auto-columns: ;', cursorOffset: -1 },
	{ word: 'grid-auto-rows', insert: 'grid-auto-rows: ;', cursorOffset: -1 },
	{ word: 'grid-auto-flow', insert: 'grid-auto-flow: ;', cursorOffset: -1 },
	{ word: 'place-items', insert: 'place-items: ;', cursorOffset: -1 },
	{ word: 'place-content', insert: 'place-content: ;', cursorOffset: -1 },
	{ word: 'place-self', insert: 'place-self: ;', cursorOffset: -1 },

	// ─── Box Model ───
	{ word: 'width', insert: 'width: ;', cursorOffset: -1 },
	{ word: 'min-width', insert: 'min-width: ;', cursorOffset: -1 },
	{ word: 'max-width', insert: 'max-width: ;', cursorOffset: -1 },
	{ word: 'height', insert: 'height: ;', cursorOffset: -1 },
	{ word: 'min-height', insert: 'min-height: ;', cursorOffset: -1 },
	{ word: 'max-height', insert: 'max-height: ;', cursorOffset: -1 },
	{ word: 'margin', insert: 'margin: ;', cursorOffset: -1 },
	{ word: 'margin-top', insert: 'margin-top: ;', cursorOffset: -1 },
	{ word: 'margin-right', insert: 'margin-right: ;', cursorOffset: -1 },
	{ word: 'margin-bottom', insert: 'margin-bottom: ;', cursorOffset: -1 },
	{ word: 'margin-left', insert: 'margin-left: ;', cursorOffset: -1 },
	{ word: 'padding', insert: 'padding: ;', cursorOffset: -1 },
	{ word: 'padding-top', insert: 'padding-top: ;', cursorOffset: -1 },
	{ word: 'padding-right', insert: 'padding-right: ;', cursorOffset: -1 },
	{ word: 'padding-bottom', insert: 'padding-bottom: ;', cursorOffset: -1 },
	{ word: 'padding-left', insert: 'padding-left: ;', cursorOffset: -1 },
	{ word: 'border', insert: 'border: ;', cursorOffset: -1 },
	{ word: 'border-top', insert: 'border-top: ;', cursorOffset: -1 },
	{ word: 'border-right', insert: 'border-right: ;', cursorOffset: -1 },
	{ word: 'border-bottom', insert: 'border-bottom: ;', cursorOffset: -1 },
	{ word: 'border-left', insert: 'border-left: ;', cursorOffset: -1 },
	{ word: 'border-width', insert: 'border-width: ;', cursorOffset: -1 },
	{ word: 'border-style', insert: 'border-style: ;', cursorOffset: -1 },
	{ word: 'border-color', insert: 'border-color: ;', cursorOffset: -1 },
	{ word: 'border-radius', insert: 'border-radius: ;', cursorOffset: -1 },
	{ word: 'border-top-left-radius', insert: 'border-top-left-radius: ;', cursorOffset: -1 },
	{ word: 'border-top-right-radius', insert: 'border-top-right-radius: ;', cursorOffset: -1 },
	{ word: 'border-bottom-left-radius', insert: 'border-bottom-left-radius: ;', cursorOffset: -1 },
	{ word: 'border-bottom-right-radius', insert: 'border-bottom-right-radius: ;', cursorOffset: -1 },
	{ word: 'border-collapse', insert: 'border-collapse: ;', cursorOffset: -1 },
	{ word: 'border-spacing', insert: 'border-spacing: ;', cursorOffset: -1 },
	{ word: 'outline', insert: 'outline: ;', cursorOffset: -1 },
	{ word: 'outline-width', insert: 'outline-width: ;', cursorOffset: -1 },
	{ word: 'outline-style', insert: 'outline-style: ;', cursorOffset: -1 },
	{ word: 'outline-color', insert: 'outline-color: ;', cursorOffset: -1 },
	{ word: 'outline-offset', insert: 'outline-offset: ;', cursorOffset: -1 },
	{ word: 'box-sizing', insert: 'box-sizing: ;', cursorOffset: -1 },
	{ word: 'box-shadow', insert: 'box-shadow: ;', cursorOffset: -1 },

	// ─── Colors & Background ───
	{ word: 'color', insert: 'color: ;', cursorOffset: -1 },
	{ word: 'background', insert: 'background: ;', cursorOffset: -1 },
	{ word: 'background-color', insert: 'background-color: ;', cursorOffset: -1 },
	{ word: 'background-image', insert: 'background-image: ;', cursorOffset: -1 },
	{ word: 'background-position', insert: 'background-position: ;', cursorOffset: -1 },
	{ word: 'background-size', insert: 'background-size: ;', cursorOffset: -1 },
	{ word: 'background-repeat', insert: 'background-repeat: ;', cursorOffset: -1 },
	{ word: 'background-attachment', insert: 'background-attachment: ;', cursorOffset: -1 },
	{ word: 'background-clip', insert: 'background-clip: ;', cursorOffset: -1 },
	{ word: 'background-origin', insert: 'background-origin: ;', cursorOffset: -1 },
	{ word: 'background-blend-mode', insert: 'background-blend-mode: ;', cursorOffset: -1 },
	{ word: 'filter', insert: 'filter: ;', cursorOffset: -1 },
	{ word: 'backdrop-filter', insert: 'backdrop-filter: ;', cursorOffset: -1 },

	// ─── Typography ───
	{ word: 'font', insert: 'font: ;', cursorOffset: -1 },
	{ word: 'font-family', insert: 'font-family: ;', cursorOffset: -1 },
	{ word: 'font-size', insert: 'font-size: ;', cursorOffset: -1 },
	{ word: 'font-weight', insert: 'font-weight: ;', cursorOffset: -1 },
	{ word: 'font-style', insert: 'font-style: ;', cursorOffset: -1 },
	{ word: 'font-variant', insert: 'font-variant: ;', cursorOffset: -1 },
	{ word: 'font-display', insert: 'font-display: ;', cursorOffset: -1 },
	{ word: 'line-height', insert: 'line-height: ;', cursorOffset: -1 },
	{ word: 'letter-spacing', insert: 'letter-spacing: ;', cursorOffset: -1 },
	{ word: 'word-spacing', insert: 'word-spacing: ;', cursorOffset: -1 },
	{ word: 'text-align', insert: 'text-align: ;', cursorOffset: -1 },
	{ word: 'text-align-last', insert: 'text-align-last: ;', cursorOffset: -1 },
	{ word: 'text-decoration', insert: 'text-decoration: ;', cursorOffset: -1 },
	{ word: 'text-decoration-line', insert: 'text-decoration-line: ;', cursorOffset: -1 },
	{ word: 'text-decoration-style', insert: 'text-decoration-style: ;', cursorOffset: -1 },
	{ word: 'text-decoration-color', insert: 'text-decoration-color: ;', cursorOffset: -1 },
	{ word: 'text-decoration-thickness', insert: 'text-decoration-thickness: ;', cursorOffset: -1 },
	{ word: 'text-transform', insert: 'text-transform: ;', cursorOffset: -1 },
	{ word: 'text-indent', insert: 'text-indent: ;', cursorOffset: -1 },
	{ word: 'text-shadow', insert: 'text-shadow: ;', cursorOffset: -1 },
	{ word: 'text-overflow', insert: 'text-overflow: ;', cursorOffset: -1 },
	{ word: 'text-wrap', insert: 'text-wrap: ;', cursorOffset: -1 },
	{ word: 'white-space', insert: 'white-space: ;', cursorOffset: -1 },
	{ word: 'word-break', insert: 'word-break: ;', cursorOffset: -1 },
	{ word: 'word-wrap', insert: 'word-wrap: ;', cursorOffset: -1 },
	{ word: 'overflow-wrap', insert: 'overflow-wrap: ;', cursorOffset: -1 },
	{ word: 'hyphens', insert: 'hyphens: ;', cursorOffset: -1 },
	{ word: 'writing-mode', insert: 'writing-mode: ;', cursorOffset: -1 },
	{ word: 'text-orientation', insert: 'text-orientation: ;', cursorOffset: -1 },
	{ word: 'direction', insert: 'direction: ;', cursorOffset: -1 },
	{ word: 'unicode-bidi', insert: 'unicode-bidi: ;', cursorOffset: -1 },
	{ word: 'vertical-align', insert: 'vertical-align: ;', cursorOffset: -1 },
	{ word: 'list-style', insert: 'list-style: ;', cursorOffset: -1 },
	{ word: 'list-style-type', insert: 'list-style-type: ;', cursorOffset: -1 },
	{ word: 'list-style-position', insert: 'list-style-position: ;', cursorOffset: -1 },
	{ word: 'list-style-image', insert: 'list-style-image: ;', cursorOffset: -1 },

	// ─── Transforms & Transitions ───
	{ word: 'transform', insert: 'transform: ;', cursorOffset: -1 },
	{ word: 'transform-origin', insert: 'transform-origin: ;', cursorOffset: -1 },
	{ word: 'transform-style', insert: 'transform-style: ;', cursorOffset: -1 },
	{ word: 'perspective', insert: 'perspective: ;', cursorOffset: -1 },
	{ word: 'perspective-origin', insert: 'perspective-origin: ;', cursorOffset: -1 },
	{ word: 'backface-visibility', insert: 'backface-visibility: ;', cursorOffset: -1 },
	{ word: 'transition', insert: 'transition: ;', cursorOffset: -1 },
	{ word: 'transition-property', insert: 'transition-property: ;', cursorOffset: -1 },
	{ word: 'transition-duration', insert: 'transition-duration: ;', cursorOffset: -1 },
	{ word: 'transition-timing-function', insert: 'transition-timing-function: ;', cursorOffset: -1 },
	{ word: 'transition-delay', insert: 'transition-delay: ;', cursorOffset: -1 },

	// ─── Animation ───
	{ word: 'animation', insert: 'animation: ;', cursorOffset: -1 },
	{ word: 'animation-name', insert: 'animation-name: ;', cursorOffset: -1 },
	{ word: 'animation-duration', insert: 'animation-duration: ;', cursorOffset: -1 },
	{ word: 'animation-timing-function', insert: 'animation-timing-function: ;', cursorOffset: -1 },
	{ word: 'animation-delay', insert: 'animation-delay: ;', cursorOffset: -1 },
	{ word: 'animation-iteration-count', insert: 'animation-iteration-count: ;', cursorOffset: -1 },
	{ word: 'animation-direction', insert: 'animation-direction: ;', cursorOffset: -1 },
	{ word: 'animation-fill-mode', insert: 'animation-fill-mode: ;', cursorOffset: -1 },
	{ word: 'animation-play-state', insert: 'animation-play-state: ;', cursorOffset: -1 },

	// ─── Scroll & Overflow ───
	{ word: 'scroll-behavior', insert: 'scroll-behavior: ;', cursorOffset: -1 },
	{ word: 'scroll-margin', insert: 'scroll-margin: ;', cursorOffset: -1 },
	{ word: 'scroll-margin-top', insert: 'scroll-margin-top: ;', cursorOffset: -1 },
	{ word: 'scroll-padding', insert: 'scroll-padding: ;', cursorOffset: -1 },
	{ word: 'scroll-padding-top', insert: 'scroll-padding-top: ;', cursorOffset: -1 },
	{ word: 'scroll-snap-type', insert: 'scroll-snap-type: ;', cursorOffset: -1 },
	{ word: 'scroll-snap-align', insert: 'scroll-snap-align: ;', cursorOffset: -1 },
	{ word: 'overscroll-behavior', insert: 'overscroll-behavior: ;', cursorOffset: -1 },

	// ─── Modern / Logical Properties ───
	{ word: 'inset', insert: 'inset: ;', cursorOffset: -1 },
	{ word: 'inset-block', insert: 'inset-block: ;', cursorOffset: -1 },
	{ word: 'inset-inline', insert: 'inset-inline: ;', cursorOffset: -1 },
	{ word: 'margin-block', insert: 'margin-block: ;', cursorOffset: -1 },
	{ word: 'margin-inline', insert: 'margin-inline: ;', cursorOffset: -1 },
	{ word: 'padding-block', insert: 'padding-block: ;', cursorOffset: -1 },
	{ word: 'padding-inline', insert: 'padding-inline: ;', cursorOffset: -1 },
	{ word: 'border-block', insert: 'border-block: ;', cursorOffset: -1 },
	{ word: 'border-inline', insert: 'border-inline: ;', cursorOffset: -1 },
	{ word: 'block-size', insert: 'block-size: ;', cursorOffset: -1 },
	{ word: 'inline-size', insert: 'inline-size: ;', cursorOffset: -1 },
	{ word: 'min-block-size', insert: 'min-block-size: ;', cursorOffset: -1 },
	{ word: 'min-inline-size', insert: 'min-inline-size: ;', cursorOffset: -1 },
	{ word: 'max-block-size', insert: 'max-block-size: ;', cursorOffset: -1 },
	{ word: 'max-inline-size', insert: 'max-inline-size: ;', cursorOffset: -1 },

	// ─── Container Queries ───
	{ word: 'container', insert: 'container: ;', cursorOffset: -1 },
	{ word: 'container-type', insert: 'container-type: ;', cursorOffset: -1 },
	{ word: 'container-name', insert: 'container-name: ;', cursorOffset: -1 },

	// ─── Table & List ───
	{ word: 'caption-side', insert: 'caption-side: ;', cursorOffset: -1 },
	{ word: 'table-layout', insert: 'table-layout: ;', cursorOffset: -1 },
	{ word: 'empty-cells', insert: 'empty-cells: ;', cursorOffset: -1 },

	// ─── Print & Content ───
	{ word: 'content', insert: 'content: ;', cursorOffset: -1 },
	{ word: 'quotes', insert: 'quotes: ;', cursorOffset: -1 },
	{ word: 'counter-reset', insert: 'counter-reset: ;', cursorOffset: -1 },
	{ word: 'counter-increment', insert: 'counter-increment: ;', cursorOffset: -1 },
	{ word: 'page-break-before', insert: 'page-break-before: ;', cursorOffset: -1 },
	{ word: 'page-break-after', insert: 'page-break-after: ;', cursorOffset: -1 },
	{ word: 'page-break-inside', insert: 'page-break-inside: ;', cursorOffset: -1 },

	// ─── Variables & Custom ───
	{ word: 'var', insert: 'var()', cursorOffset: -1 },
	{ word: 'calc', insert: 'calc()', cursorOffset: -1 },
	{ word: 'clamp', insert: 'clamp()', cursorOffset: -1 },
	{ word: 'min', insert: 'min()', cursorOffset: -1 },
	{ word: 'max', insert: 'max()', cursorOffset: -1 },

	// ─── SVG & Masking ───
	{ word: 'mask', insert: 'mask: ;', cursorOffset: -1 },
	{ word: 'mask-image', insert: 'mask-image: ;', cursorOffset: -1 },
	{ word: 'mask-size', insert: 'mask-size: ;', cursorOffset: -1 },
	{ word: 'mask-position', insert: 'mask-position: ;', cursorOffset: -1 },
	{ word: 'mask-repeat', insert: 'mask-repeat: ;', cursorOffset: -1 },
	{ word: 'fill', insert: 'fill: ;', cursorOffset: -1 },
	{ word: 'stroke', insert: 'stroke: ;', cursorOffset: -1 },
	{ word: 'stroke-width', insert: 'stroke-width: ;', cursorOffset: -1 }
];

export default completionList;